FROM fedora:43

RUN dnf install -y \
    gcc gcc-c++ make pkg-config \
    mingw64-gcc mingw64-gcc-c++ mingw64-binutils \
    mingw64-winpthreads-static

RUN dnf install -y mingw64-gtk4

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup target add x86_64-pc-windows-gnu

ENV PKG_CONFIG_ALLOW_CROSS=1
ENV PKG_CONFIG_PATH_x86_64_pc_windows_gnu=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig/
