[loader:image/svg+xml]
Exec = @EXEC@
Identifiers=ext:svg;
ExposeBaseDir = true
Fontconfig = true


[loader:image/svg+xml-compressed]
Exec = @EXEC@
Identifiers=ext:svgz;
Extension=svgz
ExposeBaseDir = true
Fontconfig = true
